apiVersion : apps/v1
kind : Deployment
metadata:
   name : app-deployment
spec:
   replicas : 1
   selector:
      matchLabels:
         app : myapp
   template : 
      metadata:
        labels:
          app : myapp
      spec:
          containers:
           - name : myapp
             image : kubedemo
             imagePullPolicy : Never
             ports : 
               - containerPort : 8080
---
apiVersion : v1
kind : Service
metadata:
   name : myapp-service
spec:
   selector : 
     app : myapp
   ports :
    - port : 8080
      targetPort : 8080
   type : NodePort
        

